spring:
  profiles:
    active: local
  application:
    name: ye-ai-code-mother-backed
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ye_ai_code_mother
    username: root
    password: 123456
server:
  port: 8123
  servlet:
    context-path: /api


# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.zuoye.yeaicodemother.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
# AI
langchain4j:
  open-ai:
    chat-model:
      base-url: https://api.deepseek.com
      api-key: <Your API Key>
      model-name: deepseek-chat
      # 最大消耗 tokens 数
      max-tokens: 8192
      # 结构化数超出
      strict-json-schema: true
      response-format: json_object
      # 最大重试次数
      max-retries: 3
      log-requests: true
      log-responses: true
